import 'package:flutter/material.dart';
import '../models/task_model.dart';

List<TaskModel> dummyTasks = [
  TaskModel(
    id: "1",
    title: 'Design UI Mockups',
    projectId: 'p1',
    dueDate: DateTime(2024, 12, 21),
    dueTime: const TimeOfDay(hour: 11, minute: 00),
    priority: 'High',
    status: 'Not Started',
    assignedMembers: ['1', '2'],
  ),
  TaskModel(
    id: "2",
    title: 'Design Login Screen',
    projectId: 'p1', 
    dueDate: DateTime(2024, 12, 21),
    dueTime: const TimeOfDay(hour: 11, minute: 00),
    priority: 'Medium',
    status: 'Not Started',
    assignedMembers: ['3'],
  ),
  TaskModel(
    id: "3",
    title: 'Write API Documentation',
    projectId: 'p2', 
    dueDate: DateTime(2024, 12, 22),
    dueTime: const TimeOfDay(hour: 1, minute: 00),
    priority: 'Low',
    status: 'In Progress',
    assignedMembers: ['4'],
  ),
  TaskModel(
    id: "4",
    title: 'Implement CRUD',
    projectId: 'p2', 
    dueDate: DateTime(2024, 12, 23),
    dueTime: const TimeOfDay(hour: 13, minute: 00),
    priority: 'Medium',
    status: 'In Progress',
    assignedMembers: ['3','4'],
  ),
  TaskModel(
    id: "5",
    title: 'Update CRUD',
    projectId: 'p2', 
    dueDate: DateTime(2024, 12, 24),
    dueTime: const TimeOfDay(hour: 17, minute: 00),
    priority: 'Medium',
    status: 'In Progress',
    assignedMembers: ['3','4'],
  ),
  TaskModel(
    id: "6",
    title: 'Create Test Cases',
    projectId: 'p3',
    dueDate: DateTime(2024, 12, 25),
    dueTime: const TimeOfDay(hour: 13, minute: 00),
    priority: 'High',
    status: 'Not Started',
    assignedMembers: ['2'],
  ),
  TaskModel(
    id: "7",
    title: 'Optimize Database Queries',
    projectId: 'p3',
    dueDate: DateTime(2024, 12, 26),
    dueTime: const TimeOfDay(hour: 15, minute: 00),
    priority: 'Medium',
    status: 'In Progress',
    assignedMembers: ['1', '4'],
  ),
  TaskModel(
    id: "8",
    title: 'Deploy Backend Services',
    projectId: 'p4',
    dueDate: DateTime(2024, 12, 27),
    dueTime: const TimeOfDay(hour: 01, minute: 00),
    priority: 'High',
    status: 'Not Started',
    assignedMembers: ['1', '3'],
  ),
  TaskModel(
    id: "9",
    title: 'Code Review for Features',
    projectId: 'p4',
    dueDate: DateTime(2024, 12, 28),
    dueTime: const TimeOfDay(hour: 17, minute: 00),
    priority: 'Low',
    status: 'In Progress',
    assignedMembers: ['2', '5'],
  ),
];
