import '../models/task_model.dart';

List<TaskModel> dummyTasks = [
  TaskModel(
    id: 1,
    title: 'Design UI Mockups',
    projectId: 'p1',
    dueDate: DateTime(2024, 12, 18),
    dueTime: '10:30 AM',
    priority: 'High',
    status: 'To-Do',
    assignedMembers: ['1', '2'],
  ),
  TaskModel(
    id: 2,
    title: 'Implement Login Screen',
    projectId: 'p1', 
    dueDate: DateTime(2024, 12, 23),
    dueTime: '01:00 PM',
    priority: 'Medium',
    status: 'Completed',
    assignedMembers: ['3'],
  ),
  TaskModel(
    id: 3,
    title: 'Write API Documentation',
    projectId: 'p2', 
    dueDate: DateTime(2024, 12, 18),
    dueTime: '11:00 AM',
    priority: 'Low',
    status: 'To-Do',
    assignedMembers: ['4'],
  ),
  TaskModel(
    id: 4,
    title: 'Implement CRUD',
    projectId: 'p2', 
    dueDate: DateTime(2024, 12, 18),
    dueTime: '11:00 AM',
    priority: 'Medium',
    status: 'To-Do',
    assignedMembers: ['3','4'],
  ),
  TaskModel(
    id: 5,
    title: 'Create Test Cases',
    projectId: 'p3',
    dueDate: DateTime(2024, 12, 25),
    dueTime: '02:00 PM',
    priority: 'High',
    status: 'To-Do',
    assignedMembers: ['2'],
  ),
  TaskModel(
    id: 6,
    title: 'Optimize Database Queries',
    projectId: 'p3',
    dueDate: DateTime(2024, 12, 22),
    dueTime: '09:00 AM',
    priority: 'Medium',
    status: 'In Progress',
    assignedMembers: ['1', '4'],
  ),
];
